apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice_template.deployment
spec:
  selector:
    matchLabels:
      app: microservice_template
  template:
    metadata:
      labels:
        app: microservice_template
    spec:
      containers:
      - name: microservice_template_dev_k8s.container
        image: microservice_template_dev_k8s.image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
